using UnityEngine;
using System.IO;
using fwp.buildor.editor;

namespace fwp.buildor
{
    /// <summary>
    /// remove folders generated by unity next to the app that must not be shipped
    /// only searched at root of build folder
    /// place before zip
    /// </summary>
    [CreateAssetMenu(menuName = BuildorHelpers._menuItem_basepath + "modules/+post do not ship", fileName = "post_doNotShip")]
    public class BoduleDoNoShip : BuildModule
    {
        public override BodulePhase Phase => BodulePhase.post;

        /// <summary>
        /// [product]_BurstDebugInformation_DoNotShip : burst debug symbols
        /// [product]_BackUpThisFolder_ButDontShipItWithYourGame : il2cpp generated cpp & symbols
        /// </summary>
        static readonly string[] patterns = new string[]
        {
            "*_DoNotShip",
            "*_ButDontShipItWithYourGame",
        };

        [Tooltip("optional, project specific folders to remove, applied after unity ones")]
        public BodulePostClearFolders clearFolders;

        protected override void doApply(BuildContext ctx)
        {
            if (ctx.profile == null)
            {
                Debug.LogWarning("do not ship : no profile");
                return;
            }

            string root = ctx.profile.BuildPath;
            if (!Directory.Exists(root))
            {
                Debug.LogWarning("do not ship : no build folder @" + root);
                return;
            }

            int count = 0;
            foreach (string pattern in patterns)
            {
                foreach (string dir in Directory.GetDirectories(root, pattern, SearchOption.TopDirectoryOnly))
                {
                    BuildProcess.ulog("-folder " + dir, this);
                    Directory.Delete(dir, true);
                    count++;
                }
            }

            BuildProcess.ulog("do not ship : removed x" + count + " @" + root, this);

            if (clearFolders != null) clearFolders.Apply(ctx);
        }

        public override string strOneLine()
        {
            string ret = base.strOneLine();
            if (clearFolders != null) ret += " +" + clearFolders.name;
            return ret;
        }
    }
}
